apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}  # Corrected reference to .Values instead of .Valuesdb
type: {{ .Values.secrets.type }}
data:
  mongo-root-username: {{ .Values.secrets.data.mongorootusername | quote }}
  mongo-root-password: {{ .Values.secrets.data.mongorootpassword | quote }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metadata.name }}  # Corrected reference to .Values instead of .Valuesdb
  labels:
    app: {{ .Values.deployment.metadata.labels.app }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}  # Corrected reference to .Values.deployment.replicaCount
  selector:
    matchLabels:
      app: {{ .Values.deployment.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.metadata.labels.app }}
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.image }}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}  # Corrected reference to .Values instead of .Valuesdb
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}  # Corrected reference to .Values instead of .Valuesdb
              key: mongo-root-password

